# Site settings
title: Spenglerei Alber Mirco
email: info@spenglerei-alber.com
pecmail: spenglerei.alber@pec.rolmail.net
description: > # this means to ignore newlines until "baseurl:"
  Spenglerei Alber Mirco
  Ihr kompetenter Ansprechpartner vor Ort
# baseurl: "stylish-portfolio-jekyll/" # the subpath of your site, e.g. /blog/
url: "https://www.spenglerei-alber.com/" # the base hostname & protocol for your site

# User setting
owner: Alber Mirco
email: info@spenglerei-alber.com
address:
  - line: Weingartweg 2
  - line: 39015 St.Leonhard i.P.
  # Feel free to add more lines here 
telephone: 347 007 5959
copyright: <a href="https://creativecommons.org/licenses/by-sa/4.0/legalcode">CC BY 4.0</a>
mwstr: 02385660218
strnr: LBR MRC 84H17 F132C


# API settings
google_api_key: AIzaSyCISFU97SQrAlTclish1CjPS5wn_v_mbrM 
# Build settings
markdown: kramdown
# Plugins
plugins:
  - jekyll-seo-tag
